module.exports = [
	"<!DOCTYPE html>",
	"<html>",
	"<head>",
	"<title>Welcome to Viridine</title>",
	"<style>",
	"body {",
	"\tbackground: #daffb0;",
	"\tmargin: 0;",
	"\tfont-family: tahoma, verdana, arial, sans-serif;",
	"\tcolor: #2e4217;",
	"}",
	"h1 {",
	"\tbackground: #63b703;",
	"\tmargin: 0;",
	"\tpadding: 8px;",
	"\tborder-bottom: 2px solid #5f7f3a;",
	"\tcolor: #eeffdb;",
	"\ttext-align: center;",
	"}",
	"li {",
	"\tmargin: 2px 0;",
	"}",
	"p, b {",
	"\tmargin: 16px 8px;",
	"}",
	"span {",
	"\tbackground: #c4f190;",
	"\tpadding: 2px;",
	"\tborder-radius: 2px;",
	"\tcolor: #558224;",
	"\tfont-family: monospace;",
	"}",
	"</style>",
	"</head>",
	"<body>",
	"<h1>Congratulations!</h1>",
	"<p>If you can see this page, it means that the Viridine server is " +
		"working correctly. You may now replace this page with your own" +
		" content.</p>",
	"<b>Server details:</b>",
	"<ul>",
	"<li>The root of this website is <span>%root%</span></li>",
	"<li>To change the server settings, edit <span>viridine.json</span></li>",
	"<li>All logs are added to <span>%logs%</span></li>",
	"</ul>",
	"<p>Thank you for using Viridine!</p>",
	"</body>",
	"</html>"
];